export const FETCH_PIZZA = 'FETCH_PIZZA';
export const FETCH_PIZZA_STARTED = 'FETCH_PIZZA_STARTED';

export const FETCH_DRINK = 'FETCH_DRINK';
export const FETCH_DRINK_STARTED = 'FETCH_DRINK_STARTED';

export const FETCH_SALAT = 'FETCH_SALAT';
export const FETCH_SALAT_STARTED = 'FETCH_SALAT_STARTED';

export const ADD_PRODUCT_TO_BASKET = 'ADD_PRODUCT_TO_BASKET';
export const ADD_PRODUCT_TO_BASKET_STARTED = 'ADD_PRODUCT_TO_BASKET_STARTED';

export const FETCH_PRODUCT_ITEMS = 'FETCH_PRODUCT_ITEMS';
export const FETCH_PRODUCT_ITEMS_STARTED = 'FETCH_PRODUCT_ITEMS_STARTED';

export const DELETE_PRODUCT_ITEMS = 'DELETE_PRODUCT_ITEMS';
export const DELETE_PRODUCT_ITEMS_STARTED = 'DELETE_PRODUCT_ITEMS_STARTED';