export const FETCH_PIZZA = 'FETCH_PIZZA';
export const FETCH_PIZZA_SUCCESS = 'FETCH_PIZZA_SUCCESS';

export const FETCH_DRINK = 'FETCH_DRINK';
export const FETCH_DRINK_SUCCESS = 'FETCH_DRINK_SUCCESS';

export const FETCH_SALAT = 'FETCH_SALAT';
export const FETCH_SALAT_SUCCESS = 'FETCH_SALAT_SUCCESS';

export const ADD_PRODUCT_TO_BASKET = 'ADD_PRODUCT_TO_BASKET';
export const ADD_PRODUCT_TO_BASKET_SUCCESS = 'ADD_PRODUCT_TO_BASKET_SUCCESS';

export const FETCH_PRODUCT_ITEMS = 'FETCH_PRODUCT_ITEMS';
export const FETCH_PRODUCT_ITEMS_SUCCESS = 'FETCH_PRODUCT_ITEMS_SUCCESS';

export const DELETE_PRODUCT_ITEMS = 'DELETE_PRODUCT_ITEMS';
export const DELETE_PRODUCT_ITEMS_SUCCESS = 'DELETE_PRODUCT_ITEMS_SUCCESS';