export const FETCH_PIZZA = 'FETCH_PIZZA';
export const FETCH_PIZZA_STARTED = 'FETCH_PIZZA_STARTED';

export const FETCH_DRINK = 'FETCH_DRINK';
export const FETCH_DRINK_STARTED = 'FETCH_DRINK_STARTED';

export const FETCH_SALAT = 'FETCH_SALAT';
export const FETCH_SALAT_STARTED = 'FETCH_SALAT_STARTED';